/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace TaskRegistry {
  export type TaskStruct = {
    taskId: string;
    publisher: AddressLike;
    volunteer: AddressLike;
    pointsReward: BigNumberish;
    completed: boolean;
    pointsClaimed: boolean;
    completedAt: BigNumberish;
    metadata: string;
    status: BigNumberish;
  };

  export type TaskStructOutput = [
    taskId: string,
    publisher: string,
    volunteer: string,
    pointsReward: bigint,
    completed: boolean,
    pointsClaimed: boolean,
    completedAt: bigint,
    metadata: string,
    status: bigint
  ] & {
    taskId: string;
    publisher: string;
    volunteer: string;
    pointsReward: bigint;
    completed: boolean;
    pointsClaimed: boolean;
    completedAt: bigint;
    metadata: string;
    status: bigint;
  };
}

export interface TaskRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "batchClaimPoints"
      | "cancelTask"
      | "claimPoints"
      | "getStats"
      | "getTask"
      | "getUserCompletedTasksCount"
      | "getUserTasks"
      | "hrtDeploymentTimestamp"
      | "hrtToken"
      | "owner"
      | "raiseDispute"
      | "registerTask"
      | "registerTaskCompletion"
      | "renounceOwnership"
      | "resolveDispute"
      | "tasks"
      | "totalPointsAwarded"
      | "totalTasksCompleted"
      | "transferOwnership"
      | "userTasks"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "PointsClaimed"
      | "TaskCancelled"
      | "TaskCompleted"
      | "TaskCreated"
      | "TaskDisputed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "batchClaimPoints",
    values: [string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelTask",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "claimPoints", values: [string]): string;
  encodeFunctionData(functionFragment: "getStats", values?: undefined): string;
  encodeFunctionData(functionFragment: "getTask", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getUserCompletedTasksCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserTasks",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hrtDeploymentTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "hrtToken", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "raiseDispute",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerTask",
    values: [string, AddressLike, AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerTaskCompletion",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resolveDispute",
    values: [string, boolean]
  ): string;
  encodeFunctionData(functionFragment: "tasks", values: [string]): string;
  encodeFunctionData(
    functionFragment: "totalPointsAwarded",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalTasksCompleted",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userTasks",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "batchClaimPoints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cancelTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimPoints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getStats", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getUserCompletedTasksCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserTasks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hrtDeploymentTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hrtToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "raiseDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerTask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerTaskCompletion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tasks", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalPointsAwarded",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalTasksCompleted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userTasks", data: BytesLike): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PointsClaimedEvent {
  export type InputTuple = [
    taskId: string,
    volunteer: AddressLike,
    points: BigNumberish,
    txHash: string
  ];
  export type OutputTuple = [
    taskId: string,
    volunteer: string,
    points: bigint,
    txHash: string
  ];
  export interface OutputObject {
    taskId: string;
    volunteer: string;
    points: bigint;
    txHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskCancelledEvent {
  export type InputTuple = [
    taskId: string,
    canceller: AddressLike,
    reason: string
  ];
  export type OutputTuple = [taskId: string, canceller: string, reason: string];
  export interface OutputObject {
    taskId: string;
    canceller: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskCompletedEvent {
  export type InputTuple = [
    taskId: string,
    publisher: AddressLike,
    volunteer: AddressLike,
    pointsReward: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    taskId: string,
    publisher: string,
    volunteer: string,
    pointsReward: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    taskId: string;
    publisher: string;
    volunteer: string;
    pointsReward: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskCreatedEvent {
  export type InputTuple = [
    taskId: string,
    publisher: AddressLike,
    pointsReward: BigNumberish
  ];
  export type OutputTuple = [
    taskId: string,
    publisher: string,
    pointsReward: bigint
  ];
  export interface OutputObject {
    taskId: string;
    publisher: string;
    pointsReward: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskDisputedEvent {
  export type InputTuple = [
    taskId: string,
    raisedBy: AddressLike,
    reason: string
  ];
  export type OutputTuple = [taskId: string, raisedBy: string, reason: string];
  export interface OutputObject {
    taskId: string;
    raisedBy: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TaskRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): TaskRegistry;
  waitForDeployment(): Promise<this>;

  interface: TaskRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  batchClaimPoints: TypedContractMethod<
    [taskIds: string[]],
    [void],
    "nonpayable"
  >;

  cancelTask: TypedContractMethod<
    [taskId: string, reason: string],
    [void],
    "nonpayable"
  >;

  claimPoints: TypedContractMethod<[taskId: string], [boolean], "nonpayable">;

  getStats: TypedContractMethod<
    [],
    [
      [bigint, bigint, string, bigint] & {
        _totalTasksCompleted: bigint;
        _totalPointsAwarded: bigint;
        _hrtTokenAddress: string;
        _hrtDeployTimestamp: bigint;
      }
    ],
    "view"
  >;

  getTask: TypedContractMethod<
    [taskId: string],
    [TaskRegistry.TaskStructOutput],
    "view"
  >;

  getUserCompletedTasksCount: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  getUserTasks: TypedContractMethod<[user: AddressLike], [string[]], "view">;

  hrtDeploymentTimestamp: TypedContractMethod<[], [bigint], "view">;

  hrtToken: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  raiseDispute: TypedContractMethod<
    [taskId: string, reason: string],
    [void],
    "nonpayable"
  >;

  registerTask: TypedContractMethod<
    [
      taskId: string,
      publisher: AddressLike,
      volunteer: AddressLike,
      pointsReward: BigNumberish,
      metadata: string
    ],
    [void],
    "nonpayable"
  >;

  registerTaskCompletion: TypedContractMethod<
    [taskId: string, metadata: string],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  resolveDispute: TypedContractMethod<
    [taskId: string, givePointsToPublisher: boolean],
    [void],
    "nonpayable"
  >;

  tasks: TypedContractMethod<
    [arg0: string],
    [
      [
        string,
        string,
        string,
        bigint,
        boolean,
        boolean,
        bigint,
        string,
        bigint
      ] & {
        taskId: string;
        publisher: string;
        volunteer: string;
        pointsReward: bigint;
        completed: boolean;
        pointsClaimed: boolean;
        completedAt: bigint;
        metadata: string;
        status: bigint;
      }
    ],
    "view"
  >;

  totalPointsAwarded: TypedContractMethod<[], [bigint], "view">;

  totalTasksCompleted: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  userTasks: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "batchClaimPoints"
  ): TypedContractMethod<[taskIds: string[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelTask"
  ): TypedContractMethod<
    [taskId: string, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimPoints"
  ): TypedContractMethod<[taskId: string], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "getStats"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, string, bigint] & {
        _totalTasksCompleted: bigint;
        _totalPointsAwarded: bigint;
        _hrtTokenAddress: string;
        _hrtDeployTimestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTask"
  ): TypedContractMethod<
    [taskId: string],
    [TaskRegistry.TaskStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserCompletedTasksCount"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserTasks"
  ): TypedContractMethod<[user: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "hrtDeploymentTimestamp"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "hrtToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "raiseDispute"
  ): TypedContractMethod<
    [taskId: string, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerTask"
  ): TypedContractMethod<
    [
      taskId: string,
      publisher: AddressLike,
      volunteer: AddressLike,
      pointsReward: BigNumberish,
      metadata: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerTaskCompletion"
  ): TypedContractMethod<
    [taskId: string, metadata: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolveDispute"
  ): TypedContractMethod<
    [taskId: string, givePointsToPublisher: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "tasks"
  ): TypedContractMethod<
    [arg0: string],
    [
      [
        string,
        string,
        string,
        bigint,
        boolean,
        boolean,
        bigint,
        string,
        bigint
      ] & {
        taskId: string;
        publisher: string;
        volunteer: string;
        pointsReward: bigint;
        completed: boolean;
        pointsClaimed: boolean;
        completedAt: bigint;
        metadata: string;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "totalPointsAwarded"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalTasksCompleted"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userTasks"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PointsClaimed"
  ): TypedContractEvent<
    PointsClaimedEvent.InputTuple,
    PointsClaimedEvent.OutputTuple,
    PointsClaimedEvent.OutputObject
  >;
  getEvent(
    key: "TaskCancelled"
  ): TypedContractEvent<
    TaskCancelledEvent.InputTuple,
    TaskCancelledEvent.OutputTuple,
    TaskCancelledEvent.OutputObject
  >;
  getEvent(
    key: "TaskCompleted"
  ): TypedContractEvent<
    TaskCompletedEvent.InputTuple,
    TaskCompletedEvent.OutputTuple,
    TaskCompletedEvent.OutputObject
  >;
  getEvent(
    key: "TaskCreated"
  ): TypedContractEvent<
    TaskCreatedEvent.InputTuple,
    TaskCreatedEvent.OutputTuple,
    TaskCreatedEvent.OutputObject
  >;
  getEvent(
    key: "TaskDisputed"
  ): TypedContractEvent<
    TaskDisputedEvent.InputTuple,
    TaskDisputedEvent.OutputTuple,
    TaskDisputedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PointsClaimed(string,address,uint256,string)": TypedContractEvent<
      PointsClaimedEvent.InputTuple,
      PointsClaimedEvent.OutputTuple,
      PointsClaimedEvent.OutputObject
    >;
    PointsClaimed: TypedContractEvent<
      PointsClaimedEvent.InputTuple,
      PointsClaimedEvent.OutputTuple,
      PointsClaimedEvent.OutputObject
    >;

    "TaskCancelled(string,address,string)": TypedContractEvent<
      TaskCancelledEvent.InputTuple,
      TaskCancelledEvent.OutputTuple,
      TaskCancelledEvent.OutputObject
    >;
    TaskCancelled: TypedContractEvent<
      TaskCancelledEvent.InputTuple,
      TaskCancelledEvent.OutputTuple,
      TaskCancelledEvent.OutputObject
    >;

    "TaskCompleted(string,address,address,uint256,uint256)": TypedContractEvent<
      TaskCompletedEvent.InputTuple,
      TaskCompletedEvent.OutputTuple,
      TaskCompletedEvent.OutputObject
    >;
    TaskCompleted: TypedContractEvent<
      TaskCompletedEvent.InputTuple,
      TaskCompletedEvent.OutputTuple,
      TaskCompletedEvent.OutputObject
    >;

    "TaskCreated(string,address,uint256)": TypedContractEvent<
      TaskCreatedEvent.InputTuple,
      TaskCreatedEvent.OutputTuple,
      TaskCreatedEvent.OutputObject
    >;
    TaskCreated: TypedContractEvent<
      TaskCreatedEvent.InputTuple,
      TaskCreatedEvent.OutputTuple,
      TaskCreatedEvent.OutputObject
    >;

    "TaskDisputed(string,address,string)": TypedContractEvent<
      TaskDisputedEvent.InputTuple,
      TaskDisputedEvent.OutputTuple,
      TaskDisputedEvent.OutputObject
    >;
    TaskDisputed: TypedContractEvent<
      TaskDisputedEvent.InputTuple,
      TaskDisputedEvent.OutputTuple,
      TaskDisputedEvent.OutputObject
    >;
  };
}
